"""Case

Revision ID: a47eadc19301
Revises:
Create Date: 2025-07-02 08:08:49.268836

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a47eadc19301"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "court_cases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lawyers", sa.JSON(), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("NEW", "READ", "PROCESSED", name="courtcasestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("gross_principal", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("interest", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("lawyer_fees", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_court_cases_name"), "court_cases", ["name"], unique=False)
    op.create_index(op.f("ix_court_cases_status"), "court_cases", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_court_cases_status"), table_name="court_cases")
    op.drop_index(op.f("ix_court_cases_name"), table_name="court_cases")
    op.drop_table("court_cases")
    # ### end Alembic commands ###
